package org.uv.tcswpractica02;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author sinoe
 */
public class EmpleadoGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmpleadoGUI
     */
    public EmpleadoGUI() {
        initComponents();
        
        setupTabla();
        panelTabla.setVisible(false);
    }
    
    private void clearForm() {
        txtClave.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtClave.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btoGuardar = new javax.swing.JButton();
        btoEliminar = new javax.swing.JButton();
        btoModificar = new javax.swing.JButton();
        btoListarTodos = new javax.swing.JButton();
        panelTabla = new javax.swing.JPanel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 450));
        setPreferredSize(new java.awt.Dimension(650, 450));

        jLabel1.setText("Clave");

        jLabel2.setText("Nombre");

        jLabel3.setText("Direccion");

        jLabel4.setText("Telefono");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btoGuardar.setText("Guardar");
        btoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoGuardarActionPerformed(evt);
            }
        });

        btoEliminar.setText("Eliminar");
        btoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoEliminarActionPerformed(evt);
            }
        });

        btoModificar.setText("Modificar");
        btoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoModificarActionPerformed(evt);
            }
        });

        btoListarTodos.setText("Listar todos");
        btoListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoListarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefono))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btoGuardar)
                            .addComponent(btoEliminar)
                            .addComponent(btoModificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(btoListarTodos)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoGuardar))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoEliminar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btoListarTodos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btoModificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void setupTabla() {
    modelTabla = new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"Clave", "Nombre", "Dirección", "Teléfono"}
    );
    tablaEmpleados = new javax.swing.JTable(modelTabla);

    // Scroll y agregar al panel creado en el diseñador
    javax.swing.JScrollPane sp = new javax.swing.JScrollPane(tablaEmpleados);
    panelTabla.setLayout(new java.awt.BorderLayout());
    panelTabla.add(sp, java.awt.BorderLayout.CENTER);

    // Opcional: altura preferida
    panelTabla.setPreferredSize(new java.awt.Dimension(600, 220));
    panelTabla.revalidate();
    panelTabla.repaint();
    }
    
    
    private boolean validateFormForSaveOrUpdate() {
        if (txtClave.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "LA CLAVE ES OBLIGATORIA");
            txtClave.requestFocus();
            return false;
        }
        if (txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "EL NOMBRE ES OBLIGATORIO");
            txtNombre.requestFocus();
            return false;
        }
        if (txtDireccion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "LA DIRRECION ES OBLIGATORIA");
            txtDireccion.requestFocus();
            return false;
        }
        if (txtTelefono.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "EL TELEFONO ES OBLIGATORIO");
            txtTelefono.requestFocus();
            return false;
        }
        try {
            Long.parseLong(txtClave.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "LA CLAVE DEBE DE SER UN NUMERO ENTERO");
            txtClave.requestFocus();
            return false;
        }
        return true;
    }

    private PojoEmpleado toPojo() {
        PojoEmpleado p = new PojoEmpleado();
        p.setClave(Long.parseLong(txtClave.getText().trim()));
        p.setNombre(txtNombre.getText().trim());
        p.setDireccion(txtDireccion.getText().trim());
        p.setTelefono(txtTelefono.getText().trim());
        return p;
    }
    
    private void btoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoGuardarActionPerformed

        DAOEmpleado dao = new DAOEmpleado ();
        PojoEmpleado pojo = new PojoEmpleado();
        pojo.setClave(Integer.parseInt(txtClave.getText()));
        pojo.setNombre(txtDireccion.getText());
        pojo.setDireccion(txtDireccion.getText());
        pojo.setTelefono(txtDireccion.getText());
        
        boolean res = dao.guardar(pojo);
        if (res)
            JOptionPane.showMessageDialog(this, "SE GUARDO CORRECTAMENTE");
        else
            JOptionPane.showMessageDialog(this, "ERROR AL GUARDAR");
    }//GEN-LAST:event_btoGuardarActionPerformed

    private void btoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoModificarActionPerformed

        if (!validateFormForSaveOrUpdate()) {
            return;
        }

        DAOEmpleado dao = new DAOEmpleado();
        PojoEmpleado pojo = toPojo();

        PojoEmpleado actualizado = dao.modificar(pojo, pojo.getClave());
        if (actualizado != null) {
            JOptionPane.showMessageDialog(this, "SE MODIFICO CORRECTAMENTE");
        } else {
            JOptionPane.showMessageDialog(this, "NO SE PUEDE MODIFICAR");
        }
    }//GEN-LAST:event_btoModificarActionPerformed

    private void btoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoEliminarActionPerformed
        String claveStr = txtClave.getText().trim();
    if (claveStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "PROPORCIONA LA CLAVE PARA ELIMINAR");
        txtClave.requestFocus();
        return;
    }
    long clave;
    try {
        clave = Long.parseLong(claveStr);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "LA CLAVE DEBE SER NUMERICA");
        txtClave.requestFocus();
        return;
    }

    int opt = JOptionPane.showConfirmDialog(
        this,
        "¿ELIMINAR EMPLEADO CON CLAVE: " + clave + "?",
        "CONFIRMAR ELIMINACION",
        JOptionPane.YES_NO_OPTION
    );
    if (opt != JOptionPane.YES_OPTION) return;

    DAOEmpleado dao = new DAOEmpleado();
    PojoEmpleado eliminado = dao.eliminar(clave);
    if (eliminado != null) {
        JOptionPane.showMessageDialog(this, "SE ELIMINO CORRECTAMENTE");
        txtClave.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtClave.requestFocus();
    } else {
        JOptionPane.showMessageDialog(this, "NO SE PUDO ELIMINAR");
    }
    }//GEN-LAST:event_btoEliminarActionPerformed

    private void btoListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoListarTodosActionPerformed
        // Si ya está visible, ocultamos (toggle off)
    if (panelTabla.isVisible()) {
        panelTabla.setVisible(false);
        panelTabla.revalidate();
        panelTabla.repaint();
        return;
    }

    // Si está oculto, intentamos cargar datos y mostrar (toggle on)
    DAOEmpleado dao = new DAOEmpleado();
    java.util.List<PojoEmpleado> lista = dao.findAll();

    if (lista == null || lista.isEmpty()) {
        JOptionPane.showMessageDialog(this, "NO HAY REGISTROS");
        // Nos quedamos ocultos si no hay nada que mostrar
        panelTabla.setVisible(false);
        panelTabla.revalidate();
        panelTabla.repaint();
        return;
    }

    // Limpiar y llenar la tabla
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaEmpleados.getModel();
    model.setRowCount(0);
    for (PojoEmpleado e : lista) {
        model.addRow(new Object[] {
            e.getClave(),
            e.getNombre(),
            e.getDireccion(),
            e.getTelefono()
        });
    }

    // Mostrar panel con la tabla
    panelTabla.setVisible(true);
    panelTabla.revalidate();
    panelTabla.repaint();
    }//GEN-LAST:event_btoListarTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btoEliminar;
    private javax.swing.JButton btoGuardar;
    private javax.swing.JButton btoListarTodos;
    private javax.swing.JButton btoModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    // Campos “tuyos”, NO generados por NetBeans
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.table.DefaultTableModel modelTabla;

}
